/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BulkOrdersRouteImport } from './routes/bulk-orders'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CustomApparelRouteImport } from './routes/custom-apparel'
import { Route as DtfPrintingRouteImport } from './routes/dtf-printing'
import { Route as DtfTransfersRouteImport } from './routes/dtf-transfers'
import { Route as EmbroideryRouteImport } from './routes/embroidery'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PrintOnDemandRouteImport } from './routes/print-on-demand'
import { Route as QuoteRequestRouteImport } from './routes/quote-request'
import { Route as ScreenPrintingRouteImport } from './routes/screen-printing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as DesignStudioIndexRouteImport } from './routes/design-studio.index'
import { Route as DesignStudioSlugRouteImport } from './routes/design-studio.$slug'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin.activity'
import { Route as AuthenticatedAdminEmployeesRouteImport } from './routes/_authenticated/admin.employees'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin.inbox'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminProductionRouteImport } from './routes/_authenticated/admin.production'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminJobsJobIdRouteImport } from './routes/_authenticated/admin.jobs.$jobId'
import { Route as AuthenticatedAdminProductsIndexRouteImport } from './routes/_authenticated/admin.products.index'
import { Route as AuthenticatedAdminProductsProductIdRouteImport } from './routes/_authenticated/admin.products.$productId'
import { Route as AccountRequestsKindIdRouteImport } from './routes/account.requests.$kind.$id'
import { Route as ApiPublicGarmentSplatRouteImport } from './routes/api/public/garment/$'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as AuthenticatedAdminRequestsKindIdRouteImport } from './routes/_authenticated/admin.requests.$kind.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrdersRoute = BulkOrdersRouteImport.update({
  id: '/bulk-orders',
  path: '/bulk-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomApparelRoute = CustomApparelRouteImport.update({
  id: '/custom-apparel',
  path: '/custom-apparel',
  getParentRoute: () => rootRouteImport,
} as any)
const DtfPrintingRoute = DtfPrintingRouteImport.update({
  id: '/dtf-printing',
  path: '/dtf-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const DtfTransfersRoute = DtfTransfersRouteImport.update({
  id: '/dtf-transfers',
  path: '/dtf-transfers',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbroideryRoute = EmbroideryRouteImport.update({
  id: '/embroidery',
  path: '/embroidery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOnDemandRoute = PrintOnDemandRouteImport.update({
  id: '/print-on-demand',
  path: '/print-on-demand',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRequestRoute = QuoteRequestRouteImport.update({
  id: '/quote-request',
  path: '/quote-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreenPrintingRoute = ScreenPrintingRouteImport.update({
  id: '/screen-printing',
  path: '/screen-printing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const DesignStudioIndexRoute = DesignStudioIndexRouteImport.update({
  id: '/design-studio/',
  path: '/design-studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignStudioSlugRoute = DesignStudioSlugRouteImport.update({
  id: '/design-studio/$slug',
  path: '/design-studio/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmployeesRoute =
  AuthenticatedAdminEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductionRoute =
  AuthenticatedAdminProductionRouteImport.update({
    id: '/production',
    path: '/production',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminJobsJobIdRoute =
  AuthenticatedAdminJobsJobIdRouteImport.update({
    id: '/jobs/$jobId',
    path: '/jobs/$jobId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsIndexRoute =
  AuthenticatedAdminProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AuthenticatedAdminProductsProductIdRoute =
  AuthenticatedAdminProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedAdminProductsRoute,
  } as any)
const AccountRequestsKindIdRoute = AccountRequestsKindIdRouteImport.update({
  id: '/requests/$kind/$id',
  path: '/requests/$kind/$id',
  getParentRoute: () => AccountRoute,
} as any)
const ApiPublicGarmentSplatRoute = ApiPublicGarmentSplatRouteImport.update({
  id: '/api/public/garment/$',
  path: '/api/public/garment/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRequestsKindIdRoute =
  AuthenticatedAdminRequestsKindIdRouteImport.update({
    id: '/requests/$kind/$id',
    path: '/requests/$kind/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-apparel': typeof CustomApparelRoute
  '/dtf-printing': typeof DtfPrintingRoute
  '/dtf-transfers': typeof DtfTransfersRoute
  '/embroidery': typeof EmbroideryRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/print-on-demand': typeof PrintOnDemandRoute
  '/quote-request': typeof QuoteRequestRoute
  '/screen-printing': typeof ScreenPrintingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/design-studio/$slug': typeof DesignStudioSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/account/': typeof AccountIndexRoute
  '/design-studio/': typeof DesignStudioIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/production': typeof AuthenticatedAdminProductionRoute
  '/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/jobs/$jobId': typeof AuthenticatedAdminJobsJobIdRoute
  '/admin/products/$productId': typeof AuthenticatedAdminProductsProductIdRoute
  '/account/requests/$kind/$id': typeof AccountRequestsKindIdRoute
  '/api/public/garment/$': typeof ApiPublicGarmentSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/requests/$kind/$id': typeof AuthenticatedAdminRequestsKindIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-apparel': typeof CustomApparelRoute
  '/dtf-printing': typeof DtfPrintingRoute
  '/dtf-transfers': typeof DtfTransfersRoute
  '/embroidery': typeof EmbroideryRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/print-on-demand': typeof PrintOnDemandRoute
  '/quote-request': typeof QuoteRequestRoute
  '/screen-printing': typeof ScreenPrintingRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/design-studio/$slug': typeof DesignStudioSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/account': typeof AccountIndexRoute
  '/design-studio': typeof DesignStudioIndexRoute
  '/shop': typeof ShopIndexRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/production': typeof AuthenticatedAdminProductionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/jobs/$jobId': typeof AuthenticatedAdminJobsJobIdRoute
  '/admin/products/$productId': typeof AuthenticatedAdminProductsProductIdRoute
  '/account/requests/$kind/$id': typeof AccountRequestsKindIdRoute
  '/api/public/garment/$': typeof ApiPublicGarmentSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/admin/products': typeof AuthenticatedAdminProductsIndexRoute
  '/admin/requests/$kind/$id': typeof AuthenticatedAdminRequestsKindIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/bulk-orders': typeof BulkOrdersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-apparel': typeof CustomApparelRoute
  '/dtf-printing': typeof DtfPrintingRoute
  '/dtf-transfers': typeof DtfTransfersRoute
  '/embroidery': typeof EmbroideryRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/print-on-demand': typeof PrintOnDemandRoute
  '/quote-request': typeof QuoteRequestRoute
  '/screen-printing': typeof ScreenPrintingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/checkout/return': typeof CheckoutReturnRoute
  '/design-studio/$slug': typeof DesignStudioSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/account/': typeof AccountIndexRoute
  '/design-studio/': typeof DesignStudioIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/employees': typeof AuthenticatedAdminEmployeesRoute
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/production': typeof AuthenticatedAdminProductionRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/jobs/$jobId': typeof AuthenticatedAdminJobsJobIdRoute
  '/_authenticated/admin/products/$productId': typeof AuthenticatedAdminProductsProductIdRoute
  '/account/requests/$kind/$id': typeof AccountRequestsKindIdRoute
  '/api/public/garment/$': typeof ApiPublicGarmentSplatRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/_authenticated/admin/products/': typeof AuthenticatedAdminProductsIndexRoute
  '/_authenticated/admin/requests/$kind/$id': typeof AuthenticatedAdminRequestsKindIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/account'
    | '/auth'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-apparel'
    | '/dtf-printing'
    | '/dtf-transfers'
    | '/embroidery'
    | '/faq'
    | '/how-it-works'
    | '/print-on-demand'
    | '/quote-request'
    | '/screen-printing'
    | '/admin'
    | '/checkout/return'
    | '/design-studio/$slug'
    | '/shop/$slug'
    | '/account/'
    | '/design-studio/'
    | '/shop/'
    | '/admin/activity'
    | '/admin/employees'
    | '/admin/inbox'
    | '/admin/notifications'
    | '/admin/production'
    | '/admin/products'
    | '/admin/'
    | '/admin/jobs/$jobId'
    | '/admin/products/$productId'
    | '/account/requests/$kind/$id'
    | '/api/public/garment/$'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/admin/products/'
    | '/admin/requests/$kind/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/auth'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-apparel'
    | '/dtf-printing'
    | '/dtf-transfers'
    | '/embroidery'
    | '/faq'
    | '/how-it-works'
    | '/print-on-demand'
    | '/quote-request'
    | '/screen-printing'
    | '/checkout/return'
    | '/design-studio/$slug'
    | '/shop/$slug'
    | '/account'
    | '/design-studio'
    | '/shop'
    | '/admin/activity'
    | '/admin/employees'
    | '/admin/inbox'
    | '/admin/notifications'
    | '/admin/production'
    | '/admin'
    | '/admin/jobs/$jobId'
    | '/admin/products/$productId'
    | '/account/requests/$kind/$id'
    | '/api/public/garment/$'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/admin/products'
    | '/admin/requests/$kind/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/about'
    | '/account'
    | '/auth'
    | '/bulk-orders'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/custom-apparel'
    | '/dtf-printing'
    | '/dtf-transfers'
    | '/embroidery'
    | '/faq'
    | '/how-it-works'
    | '/print-on-demand'
    | '/quote-request'
    | '/screen-printing'
    | '/_authenticated/admin'
    | '/checkout/return'
    | '/design-studio/$slug'
    | '/shop/$slug'
    | '/account/'
    | '/design-studio/'
    | '/shop/'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/employees'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/production'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/jobs/$jobId'
    | '/_authenticated/admin/products/$productId'
    | '/account/requests/$kind/$id'
    | '/api/public/garment/$'
    | '/api/public/media/$'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/_authenticated/admin/products/'
    | '/_authenticated/admin/requests/$kind/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  BulkOrdersRoute: typeof BulkOrdersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomApparelRoute: typeof CustomApparelRoute
  DtfPrintingRoute: typeof DtfPrintingRoute
  DtfTransfersRoute: typeof DtfTransfersRoute
  EmbroideryRoute: typeof EmbroideryRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PrintOnDemandRoute: typeof PrintOnDemandRoute
  QuoteRequestRoute: typeof QuoteRequestRoute
  ScreenPrintingRoute: typeof ScreenPrintingRoute
  DesignStudioSlugRoute: typeof DesignStudioSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  DesignStudioIndexRoute: typeof DesignStudioIndexRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicGarmentSplatRoute: typeof ApiPublicGarmentSplatRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-orders': {
      id: '/bulk-orders'
      path: '/bulk-orders'
      fullPath: '/bulk-orders'
      preLoaderRoute: typeof BulkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-apparel': {
      id: '/custom-apparel'
      path: '/custom-apparel'
      fullPath: '/custom-apparel'
      preLoaderRoute: typeof CustomApparelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtf-printing': {
      id: '/dtf-printing'
      path: '/dtf-printing'
      fullPath: '/dtf-printing'
      preLoaderRoute: typeof DtfPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dtf-transfers': {
      id: '/dtf-transfers'
      path: '/dtf-transfers'
      fullPath: '/dtf-transfers'
      preLoaderRoute: typeof DtfTransfersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embroidery': {
      id: '/embroidery'
      path: '/embroidery'
      fullPath: '/embroidery'
      preLoaderRoute: typeof EmbroideryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print-on-demand': {
      id: '/print-on-demand'
      path: '/print-on-demand'
      fullPath: '/print-on-demand'
      preLoaderRoute: typeof PrintOnDemandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-request': {
      id: '/quote-request'
      path: '/quote-request'
      fullPath: '/quote-request'
      preLoaderRoute: typeof QuoteRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screen-printing': {
      id: '/screen-printing'
      path: '/screen-printing'
      fullPath: '/screen-printing'
      preLoaderRoute: typeof ScreenPrintingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/design-studio/': {
      id: '/design-studio/'
      path: '/design-studio'
      fullPath: '/design-studio/'
      preLoaderRoute: typeof DesignStudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-studio/$slug': {
      id: '/design-studio/$slug'
      path: '/design-studio/$slug'
      fullPath: '/design-studio/$slug'
      preLoaderRoute: typeof DesignStudioSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/employees': {
      id: '/_authenticated/admin/employees'
      path: '/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AuthenticatedAdminEmployeesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/production': {
      id: '/_authenticated/admin/production'
      path: '/production'
      fullPath: '/admin/production'
      preLoaderRoute: typeof AuthenticatedAdminProductionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs/$jobId': {
      id: '/_authenticated/admin/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/admin/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedAdminJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products/': {
      id: '/_authenticated/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AuthenticatedAdminProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/_authenticated/admin/products/$productId': {
      id: '/_authenticated/admin/products/$productId'
      path: '/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AuthenticatedAdminProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedAdminProductsRoute
    }
    '/account/requests/$kind/$id': {
      id: '/account/requests/$kind/$id'
      path: '/requests/$kind/$id'
      fullPath: '/account/requests/$kind/$id'
      preLoaderRoute: typeof AccountRequestsKindIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/api/public/garment/$': {
      id: '/api/public/garment/$'
      path: '/api/public/garment/$'
      fullPath: '/api/public/garment/$'
      preLoaderRoute: typeof ApiPublicGarmentSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/requests/$kind/$id': {
      id: '/_authenticated/admin/requests/$kind/$id'
      path: '/requests/$kind/$id'
      fullPath: '/admin/requests/$kind/$id'
      preLoaderRoute: typeof AuthenticatedAdminRequestsKindIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminProductsRouteChildren {
  AuthenticatedAdminProductsProductIdRoute: typeof AuthenticatedAdminProductsProductIdRoute
  AuthenticatedAdminProductsIndexRoute: typeof AuthenticatedAdminProductsIndexRoute
}

const AuthenticatedAdminProductsRouteChildren: AuthenticatedAdminProductsRouteChildren =
  {
    AuthenticatedAdminProductsProductIdRoute:
      AuthenticatedAdminProductsProductIdRoute,
    AuthenticatedAdminProductsIndexRoute: AuthenticatedAdminProductsIndexRoute,
  }

const AuthenticatedAdminProductsRouteWithChildren =
  AuthenticatedAdminProductsRoute._addFileChildren(
    AuthenticatedAdminProductsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminEmployeesRoute: typeof AuthenticatedAdminEmployeesRoute
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminProductionRoute: typeof AuthenticatedAdminProductionRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminJobsJobIdRoute: typeof AuthenticatedAdminJobsJobIdRoute
  AuthenticatedAdminRequestsKindIdRoute: typeof AuthenticatedAdminRequestsKindIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
  AuthenticatedAdminEmployeesRoute: AuthenticatedAdminEmployeesRoute,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminProductionRoute: AuthenticatedAdminProductionRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminJobsJobIdRoute: AuthenticatedAdminJobsJobIdRoute,
  AuthenticatedAdminRequestsKindIdRoute: AuthenticatedAdminRequestsKindIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccountRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountRequestsKindIdRoute: typeof AccountRequestsKindIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountRequestsKindIdRoute: AccountRequestsKindIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  BulkOrdersRoute: BulkOrdersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomApparelRoute: CustomApparelRoute,
  DtfPrintingRoute: DtfPrintingRoute,
  DtfTransfersRoute: DtfTransfersRoute,
  EmbroideryRoute: EmbroideryRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PrintOnDemandRoute: PrintOnDemandRoute,
  QuoteRequestRoute: QuoteRequestRoute,
  ScreenPrintingRoute: ScreenPrintingRoute,
  DesignStudioSlugRoute: DesignStudioSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  DesignStudioIndexRoute: DesignStudioIndexRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicGarmentSplatRoute: ApiPublicGarmentSplatRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
